
DATA_DIR = "/content/drive/MyDrive/AtlasData"
VIDEO_DIR = f"{DATA_DIR}/storage/videos"
THUMBNAIL_DIR = f"{DATA_DIR}/storage/thumbnails"

DRIVE_DB_PATH = f"{DATA_DIR}/atlas.db"
LOCAL_DB_PATH = "/content/atlas_local.db"
DB_PATH = DRIVE_DB_PATH

IA_RESULTS_PER_QUERY = 20
IA_MAX_FILESIZE_MB = 80
IA_MAX_DURATION_SECONDS = 600

SCENE_THRESHOLD = 27.0
MIN_SCENE_LEN_SECONDS = 1.0
CHECKPOINT_EVERY = 10

CAPTION_MIN_DURATION = 0.5
CAPTION_MAX_DURATION = 60.0
CAPTION_BATCH_SIZE = 16
CAPTION_CHECKPOINT_EVERY_BATCHES = 5

EMBED_MODEL_NAME = "all-MiniLM-L6-v2"
FAISS_INDEX_PATH = f"{DATA_DIR}/atlas.faiss"
FAISS_IDS_PATH = f"{DATA_DIR}/atlas_faiss_ids.npy"
EMBED_BATCH_SIZE = 64

RELEVANCE_WEIGHT = 1.0
USAGE_PENALTY_WEIGHT = 0.15
RECENCY_PENALTY_WEIGHT = 0.10

PRODUCTION_DIR = f"{DATA_DIR}/production"
SCRIPT_PATH = f"{PRODUCTION_DIR}/script.txt"
WHISPER_MODEL_SIZE = "medium"
PARAGRAPH_TIMINGS_PATH = f"{PRODUCTION_DIR}/paragraph_timings.json"
WHISPER_WORDS_PATH = f"{PRODUCTION_DIR}/whisper_words.json"
TIMELINE_OUTPUT_PATH = f"{PRODUCTION_DIR}/timeline.json"
MIN_CLIP_DURATION_SECONDS = 1.5
MAX_CLIPS_PER_PARAGRAPH = 6
SEARCH_CANDIDATES_PER_PARAGRAPH = 15

EDITED_TIMELINE_PATH = f"{PRODUCTION_DIR}/timeline_edited.json"
KEN_BURNS_MIN_ZOOM = 1.0
KEN_BURNS_MAX_ZOOM = 1.12
KEN_BURNS_MAX_PAN_FRACTION = 0.08
CROSSFADE_DURATION_SECONDS = 0.4
MIN_DURATION_FOR_PAN = 3.0

RENDER_WORK_DIR = "/content/render_work"
RENDER_WIDTH = 1920
RENDER_HEIGHT = 1080
RENDER_FPS = 30
FINAL_VIDEO_PATH = f"{PRODUCTION_DIR}/video.mp4"

GRADE_CONTRAST = 1.08
GRADE_SATURATION = 0.92
GRADE_BRIGHTNESS = -0.02
GRADE_VIGNETTE_STRENGTH = 0.25

GEMINI_MODEL_NAME = "gemini-2.5-flash"
GRAPHICS_PLAN_PATH = f"{PRODUCTION_DIR}/graphics_plan.json"
GRAPHICS_PLAN_TIMED_PATH = f"{PRODUCTION_DIR}/graphics_plan_timed.json"

GRAPHICS_WORK_DIR = "/content/graphics_work"
GRAPHICS_DISPLAY_DURATION = 4.5

TITLE_FONT_PATH = "/content/Atlas/assets/fonts/Anton-Regular.ttf"
BODY_FONT_PATH = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"
BODY_FONT_REGULAR_PATH = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
SERIF_FONT_PATH = "/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf"

NAVY_DEEP = (6, 14, 36, 255)
NAVY_PANEL = (8, 18, 44, 222)
GFX_WHITE = (255, 255, 255, 255)
GFX_OFFWHITE = (225, 231, 242, 255)
GFX_ORANGE = (255, 138, 24, 255)
GFX_SHADOW = (0, 0, 0, 150)

VOICES_DIR = f"{DATA_DIR}/voices"
TTS_MODEL_NAME = "Qwen/Qwen3-TTS-12Hz-1.7B-Base"
TTS_CHUNK_MAX_CHARS = 240
TTS_WORK_DIR = "/content/tts_work"
NARRATION_OUTPUT_PATH = f"{PRODUCTION_DIR}/narration.mp3"
