
DATA_DIR = "/content/drive/MyDrive/AtlasData"
VIDEO_DIR = f"{DATA_DIR}/storage/videos"
THUMBNAIL_DIR = f"{DATA_DIR}/storage/thumbnails"

DRIVE_DB_PATH = f"{DATA_DIR}/atlas.db"
LOCAL_DB_PATH = "/content/atlas_local.db"
DB_PATH = DRIVE_DB_PATH

IA_RESULTS_PER_QUERY = 20
IA_MAX_FILESIZE_MB = 80
IA_MAX_DURATION_SECONDS = 600

SCENE_THRESHOLD = 27.0
MIN_SCENE_LEN_SECONDS = 1.0
CHECKPOINT_EVERY = 10

CAPTION_MIN_DURATION = 0.5
CAPTION_MAX_DURATION = 60.0
CAPTION_BATCH_SIZE = 16
CAPTION_CHECKPOINT_EVERY_BATCHES = 5

EMBED_MODEL_NAME = "all-MiniLM-L6-v2"
FAISS_INDEX_PATH = f"{DATA_DIR}/atlas.faiss"
FAISS_IDS_PATH = f"{DATA_DIR}/atlas_faiss_ids.npy"
EMBED_BATCH_SIZE = 64

RELEVANCE_WEIGHT = 1.0
USAGE_PENALTY_WEIGHT = 0.15
RECENCY_PENALTY_WEIGHT = 0.10

PRODUCTION_DIR = f"{DATA_DIR}/production"
SCRIPT_PATH = f"{PRODUCTION_DIR}/script.txt"
WHISPER_MODEL_SIZE = "medium"
PARAGRAPH_TIMINGS_PATH = f"{PRODUCTION_DIR}/paragraph_timings.json"
TIMELINE_OUTPUT_PATH = f"{PRODUCTION_DIR}/timeline.json"
MIN_CLIP_DURATION_SECONDS = 1.5
MAX_CLIPS_PER_PARAGRAPH = 6
SEARCH_CANDIDATES_PER_PARAGRAPH = 15

EDITED_TIMELINE_PATH = f"{PRODUCTION_DIR}/timeline_edited.json"
KEN_BURNS_MIN_ZOOM = 1.0
KEN_BURNS_MAX_ZOOM = 1.12          # max 12% zoom over the clip's duration
KEN_BURNS_MAX_PAN_FRACTION = 0.08  # max 8% of frame width/height for pan drift
CROSSFADE_DURATION_SECONDS = 0.4
MIN_DURATION_FOR_PAN = 3.0         # clips shorter than this get zoom-only, no pan (too subtle to read)
